### ISSUE TITLE
Test script tdl-client-python python package

### ISSUE THREAD

**Issue by neomatrix369** [julianghionoiu/tdl-client-python#20]
When programmatic changes are made to `tdl-client-python` or changes are made to the package creation setup file(s) i.e. `setup.cfg` or `setup.py` and/or any other dependencies, it would be a good idea to have something to quickly check if the final artifact that gets pushed to the python repository/repositories does actually work.

This is raised on the back of the recent PR (#19) where a couple of important details were overlooked/missed.

This test script can be run manually and/or via CodeShip every time a new artifact is built or just before the release build is generated.

**Comment by julianghionoiu** [comment]
No need for this functionality as you will now pretty quick if something went wrong when we pull the dependency into the runner.

**Comment by neomatrix369** [comment]
> No need for this functionality as you will now pretty quick if something went wrong when we pull the dependency into the runner.

I'm sure as humans we will forget the next time we come across this work or a related project. Such automatic checks can always help - but it's not my call.
